### ISSUE TITLE
How to sync an existing terraform-module with original template

### ISSUE THREAD

**Issue by pdmthorsrud** [fredrikhgrelland/vagrant-hashistack#207]
## Original problem
If someone has made a TF-module with a version of the template and want to update to the newest version.

Add section on how to rebase, or is that excessive?

## Todo
- [ ] define strategy how to sync original template with just-created-module
- [ ] Update doc

## Repos
- [ ] [terraform-nomad-minio](https://github.com/fredrikhgrelland/terraform-nomad-minio)
- [ ] [terraform-nomad-postgres](https://github.com/fredrikhgrelland/terraform-nomad-postgres)
- [ ] [terraform-nomad-hive](https://github.com/fredrikhgrelland/terraform-nomad-hive)
- [ ] [terraform-nomad-presto](https://github.com/fredrikhgrelland/terraform-nomad-presto)
- [ ] [terraform-nomad-redash](https://github.com/fredrikhgrelland/terraform-nomad-redash)

**Comment by fredrikhgrelland** [comment]
If so, make it a separate file. Still could be worth while.

**Comment by zhenik** [comment]
#217

**Comment by zhenik** [comment]
Not relevant anymore in this repository. Moved to https://github.com/fredrikhgrelland/vagrant-hashistack-template/issues/32
