### ISSUE TITLE
Documentation refactor [epic]

### ISSUE THREAD

**Issue by zhenik** [fredrikhgrelland/vagrant-hashistack#253]
## Root README
- [ ] Logo
- [ ] Header section #257 
- [ ] Description section #257
- [ ] Install prerequisites section #257
  - [ ] Proxy section #254 #257
- [ ] Build section #257
- [ ] Configuration section #257
- [ ] Usage section #257
- [ ] Test section #257
- [ ] Github actions section #210 #257 (conflict)
- [ ] Contribution section #257
- [ ] Diagram #257

## Template README
- [x] Hashicorp usage section #233 
- [x] Development process section #232
- [x] Githab actions section #210
