### ISSUE TITLE
Upstream to template

### ISSUE THREAD

**Issue by zhenik** [fredrikhgrelland/vagrant-hashistack#306]
#### Documentation
- [x] [Prerequisites section](https://github.com/fredrikhgrelland/terraform-nomad-presto/pull/7#discussion_r484764278)
- [ ] Getting started guide #272 

#### Makefile
- [x] [Linter check on local machine. Docker. Makefile](https://github.com/fredrikhgrelland/terraform-nomad-presto/pull/7/files#diff-b67911656ef5d18c4ae36cb6741b7965R16-R17) #309 
- [x] [addtional vagrant command: status](https://github.com/fredrikhgrelland/terraform-nomad-presto/pull/7/files#diff-b67911656ef5d18c4ae36cb6741b7965R55-R56) #309 
- [ ] [terraform fmt -recursive -- to format terraform files](https://github.com/fredrikhgrelland/terraform-nomad-hive/blob/master/format.sh#L2) [#10](https://github.com/fredrikhgrelland/vagrant-hashistack-template/issues/10)
- [ ] `Make:clean` command does proper clean up. (remove all temporary folders and files) [#8](https://github.com/fredrikhgrelland/vagrant-hashistack-template/issues/8)
- [x] Linter for `tf` files #301 
- [ ] [Check for consul binary](https://github.com/fredrikhgrelland/terraform-nomad-redash/blob/e8dec7d3c4f1f5f2330a4def49cbaaf04a0bc5a8/Makefile#L12) [#9](https://github.com/fredrikhgrelland/vagrant-hashistack-template/issues/9)

**Comment by zhenik** [comment]
Each task is extracted to separate issue
