### ISSUE TITLE
Documentation update for release 0.6.0

### ISSUE THREAD

**Issue by zhenik** [fredrikhgrelland/vagrant-hashistack#399]
- [x] [Build section](https://github.com/fredrikhgrelland/vagrant-hashistack#build) @dangernil  #410 
- [x] [Configuration section](https://github.com/fredrikhgrelland/vagrant-hashistack#configuration) @claesgill #401  
- [x] [# 398 Life-cycle diagram](https://github.com/fredrikhgrelland/vagrant-hashistack/issues/398) @zhenik #411
